### PR TITLE
add healthcheck for clusters

### PR DESCRIPTION
**Pull request by docwhat**
fixes issue #4

Signed-off-by: Christian Höltje <docwhat@gerf.org>

### CODE REVIEW

**Comment by nero120** [comment]
Many thanks @docwhat, will test and respond shortly.

**Comment by nero120** [comment]
@docwhat if I change `settings.json` to the following:

```
{
  "db": {
    "host": "db"
  },
  "status": {
    "online": false
  }
}
```

the api no longer starts at all. If `status.online` is set to `false` the service should still start so the docs page is visible, as below:

image

**Comment by docwhat** [comment]
My reason for adding this was that it returned status 2 despite everything being up. 

Restarting the API container fixed it. 

What status does the API return in the case above? 3?

If so then that is an easy fix. 



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by docwhat** [comment]
I can't reproduce it.  I'll poke at it as time permits.

The `docker-compose.yml` isn't really setup for `docker swarm` but I can get away with `docker exec curl ...` to check the status.

Maybe you need to rebuild using `--no-cache` or otherwise clean out your cache?

**Comment by nero120** [comment]
Healthcheck has been added in v1.1.13. Thanks for your contribution @docwhat!

**Pull request closed without merging**
